### ISSUE TITLE
Native compiling: Requires AM3359_PRU.cmd and bin.cmd

### ISSUE THREAD

**Issue by vmayoral** [BeaglePilot/PRUSS-C#2]
Following [this](https://github.com/BeaglePilot/PRUSS-C#for-arm-systems) recipe i get the following issues (paths are set correctly):

```
clpru --silicon_version=3 -o1 blinkled_pru.c -z AM3359_PRU.cmd -o PRU_tests.out -m PRU_tests.map
<Linking>
"/tmp/00918WdONl3", line 5: error: cannot find file "AM3359_PRU.cmd"
error: errors encountered during linking; "PRU_tests.out" not built

>> Compilation failure
```

Although the file is in the path it seems that clpru doesn't find it. Maybe there's an option to say so. For now i just copied the file to the `blinked` folder and it compiles.

Similartly, `hexpru bin.cmd PRU_tests.out` doesn't work because it doesn't find `bin.cmd`.

**Comment by bugobliterator** [comment]
You have to have both of them in the same directory from where you compile. These files just contains additional arguments for the compiler and hex converter.

**Comment by vmayoral** [comment]
I'm compiling from `PRUSS-C/am335x_pru_package/pru_sw/example_apps/blinkled`, no there by default. What am I doing wrong?

**Comment by vmayoral** [comment]
@bugobliterator cloned again the code and compiled the app loader again from the repo. Same problem as described. The commands don't find `AM3359_PRU`.cmd and `bin.cmd`. I have to copy them manually to succeed with the `clpru` and the `hexpru` commands (respectively)

**Comment by bugobliterator** [comment]
yeah, vmayoral you've to either copy as you have done or pass the full path, but i've resolved it inside the starterware make, so no need to pass anything, but you've to have the PRU compiler dir inside PRU_LIB. But we can change that if you want but that will lead to one more environment variable export.

**Comment by vmayoral** [comment]
solved then, i was going crazy thinking that my binaries were for some reason wrong :). Thanks!

**Comment by erenbasturk** [comment]
Hi, I want to compile it on my BBB. In Basic Command for Compilation section for arm systems, I don' t have ARMLinuxA8 directory. What can I do to complete?

(export PRU_C_DIR="/path/to/ARMLinuxA8/include;/path/to/ARMLinuxA8/lib)

**Comment by anujdeshpande** [comment]
@erenbasturk You will require the PRU C compiler for that. A semi-public release might be available on request at the #beagle channel on Freenode.
