### ISSUE TITLE
Native compiling: undefined reference

### ISSUE THREAD

**Issue by vmayoral** [BeaglePilot/PRUSS-C#3]
From `blinked' dir, when doing`make CROSS_COMPILE=""`:

```
gcc -Wall -I../../app_loader/include -D__DEBUG -O2 -mtune=cortex-a8 -march=armv7-a -o ../bin/blinkled obj/blinkled.o -L../../app_loader/lib -lprussdrv
obj/blinkled.o: In function `main':
blinkled.c:(.text.startup+0xe6): undefined reference to `prussdrv_load_datafile'
/lib/../lib/libprussdrv.so: undefined reference to `pthread_join'
/lib/../lib/libprussdrv.so: undefined reference to `pthread_create'
collect2: ld returned 1 exit status
make: *** [../bin/blinkled] Error 1
```

Should be further inspected.

**Comment by bugobliterator** [comment]
I'm not getting any error during native compilation, It is working smoothly. The error you got was given to me too when i tried to compile blinkled with libprussdrv.so of pypruss replacing the original generated one, check out if you are not having another library loaded inside the environment

**Comment by vmayoral** [comment]
Probably i had some issue with the library. Recreated it and went fine.
