### ISSUE TITLE
Executing blinked

### ISSUE THREAD

**Issue by vmayoral** [BeaglePilot/PRUSS-C#5]
Followed README (basic command for compilation + Compiling your BBB main app).

Then when executing:

```
export LD_LIBRARY_PATH=/usr/local/lib
modprobe uio_pruss
echo BB-BONE-PRU-01 > /sys/devices/bone_capemgr.8/slots #activate the PRU 0
```

and then when executing `./blinked`:

```
INFO: Starting PRU_memAccess_DDR_PRUsharedRAM example.
        INFO: Initializing example.
        INFO: Loading Data. failed
```

@bugobliterator any idea why this might be happening?

**Comment by vmayoral** [comment]
copied `data.bin`(from `../blinked`dir) and:

```

INFO: Starting PRU_memAccess_DDR_PRUsharedRAM example.
        INFO: Initializing example.
        INFO: Loading Data. success
        INFO: Executing example.
 success
        INFO: Waiting for HALT command.
^C
```

no LEDs flashing.

**Comment by bugobliterator** [comment]
just try copying the `libprussdrv.so` generated in step _Compiling App Loader_ inside any directory say `/home/root/` and then `export LD_LIBRARY_PATH=/home/root`. I guess it should work fine then.

**Comment by vmayoral** [comment]
problem was solved putting both `data.bin` and `text.bin`in the same directory as the `blinked` executable.
